//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airlinesEDOnDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public string BookingID { get; set; }
        public int CusId { get; set; }
        public int FlightId { get; set; }
        public int NoOfTickets { get; set; }
        public System.DateTime Fdate { get; set; }
        public int Amount { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual flightDetail flightDetail { get; set; }
    }
}
